### ISSUE TITLE
Move CI to GitHub Actions or Azure Pipelines

### ISSUE THREAD

**Issue by g-plane** [buntis/buntis#13]
GitHub Actions and Azure Pipelines are completely free for open source projects, while CircleCI has limitation that we only can run no more than 1000 minutes per month.

**Comment by KFlash** [comment]
Do you want to do a PR?

**Comment by g-plane** [comment]
I can, but it seems that GitHub Actions isn't enabled for this organization.

**Comment by KFlash** [comment]
GitHub Actions still in beta
