### ISSUE TITLE
Extra comma in Variable Declaration makes it fail

### ISSUE THREAD

**Issue by nchanged** [buntis/buntis#16]
Extra comma in Variable Declaration makes it fail
```
var foo = function(){}, boo = function(){},
```

Gives
```
Unexpected token end of source
```

Expected to be parsed as if there was no comma at the end

```
var foo = function(){}, boo = function(){}
```

**Comment by KFlash** [comment]
I'm not around now, but did you even try to parse this in the REPL before reporting an issue? With whatever option I'm turning on  I can't reproduce it without the extra colon you put in the end of it.

And I can't see any semicolon? 

Anyway. It's invalid syntax you are trying to parse. Try it in the TS playground as well. The colon is invalid.

**Comment by nchanged** [comment]
@KFlash sorry not semicolon! A comma!

**Comment by nchanged** [comment]
and yes, of course, why do you think I'll be reporting something that's not confirmed?
<img width="970" alt="Screenshot 2019-10-11 10 20 10" src="https://user-images.githubusercontent.com/1629088/66636094-ca596980-ec10-11e9-893f-9e9b018446de.png">

**Comment by nchanged** [comment]
The issue is.. that even if typescript compiles it, it does it wrong...
However, it compiles this one:

```
var foo = function () { }, boo = function () { },
var a = 1;
```

But goes nuts with:

```
var foo = function () { }, boo = function () { },
alert(1)
```

**Comment by nchanged** [comment]
@KFlash no worries, I realised that typescript still compiles it even with a stupid error like this.
