### ISSUE TITLE
Errors on typescript interface methods that have a union of parameter types

### ISSUE THREAD

**Issue by nspaeth** [buntis/buntis#20]
**Code**

```ts
interface MyInterface {
  	myMethod(string | number): string
}
```

**Expected behavior:**
Should not error.

**Actual behavior:**
'Line 2, column 20: Expected ,'

**Comment by nchanged** [comment]
```
class Hey {
  method(oi : Foo & Bar){

  }
}
```

THat one fails too

**Comment by KFlash** [comment]
PR's are welcome :) Not much time this days.

**Comment by KFlash** [comment]
@nchanged Is it the 4th or 5th time now you report something as a bug that is either 1) a bug or 2) already fixed?

Try your code in the Buntis REPL and it parse :)

**Comment by nspaeth** [comment]
Hmm. Although my original code snippet does compile in the typescript compiler, it might be invalid syntax. The argument on the method isn't named, as in:

```ts
interface MyInterface {
  	myMethod(x: string | number): string
}
```
Not sure how you want to handle that.

**Comment by KFlash** [comment]
@nspaeth Your first code example is invalid. No type annotation.  The last one  you pasted in here is valid, and works if you try it in the Buntis REPL

The "invalid" example @nchanged pasted in here was valid, and Buntis have no problem to parse it.
