### ISSUE TITLE
Optional parameters throw error

### ISSUE THREAD

**Issue by nchanged** [buntis/buntis#23]
```
const foo = (a?, payload) => {}
```

​
>> Line 1, column 16: Unexpected token ,

**Comment by nspaeth** [comment]
More specifically, optional parameters followed by other parameters throw errors.
For example
```
const foo = (a?) => {} // Works,
const bar = (a, b?, c) => {} // errors
const baz = (a?, b) => {} // errors
```

**Comment by KFlash** [comment]
@nchanged @nchanged You two can argue who will create a PR for this. I'm still busy with RL issues :)

**Comment by jpike88** [comment]
@nspaeth can you clarify if the following case would work:

```const foo = (a, b?, c?) => {}```

**Comment by jpike88** [comment]
wow it doesn't work. this is kind of critical, loads of projects use multiple optional variables

**Comment by jpike88** [comment]
fails on this code too

```public static showNewTaskDialog = async (plant: Plant, isConnect: boolean, initialTitle?: string): Promise<boolean> => {}```

**Comment by nchanged** [comment]
@KFlash is jet lagged ;-)

**Comment by KFlash** [comment]
See #25 . File bugs against that one.
