### ISSUE TITLE
Property extends throws an error when inside object/interface

### ISSUE THREAD

**Issue by nchanged** [buntis/buntis#24]
```
export interface Foo {
  config?: {
    extends?: string;
  };
}
```
> Line 4, column 12: Property or signature expected

It shouldn't throw on this.

**Comment by KFlash** [comment]
@nchanged Waiting for your PR :)

**Comment by nchanged** [comment]
It's 1 minute for you, 3 hours for me, please fix it Kenny )

**Comment by KFlash** [comment]
Soon as I find time I will :)

**Comment by KFlash** [comment]
@nchanged This doesn't throw, so closing.
