### ISSUE TITLE
EStree TS AST output

### ISSUE THREAD

**Issue by KFlash** [buntis/buntis#3]
The returned TS AST follows [this](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/typescript-estree/src/ts-estree/ts-estree.ts).

**Note:** The returned AST will not be Babel compatible because Babel obvious have created their own TS AST nodes, and / or doing things in their own way which complicates things for me, so I'm simply doing things my way and choose to be at least `ESLint` compatible.

One example to illustrate the Babel issue is this one:  `interface I { m?(): void; }`

In TypeScript this void type annotation is a `returnType` property value. In the Babel parser this is a `typeAnnotation` wrapped inside another `typeAnnotation` AST node. As [seen here](https://github.com/babel/babel/blob/master/packages/babel-parser/test/fixtures/typescript/interface/method-optional/output.json#L112).

cc / @nchanged @aladdin-add

**Comment by nchanged** [comment]
I wouldn't bother about Babel @KFlash they always had their "own" AST nodes...

**Comment by KFlash** [comment]
There are more challenges than that :) In TypeScript itself many places `name` are used, but in the ESTree TS AST types I try to follow `name` is `id`. And some nodes are different and / or not existing.

I need to investigate and adjust the AST in the end.

**Comment by KFlash** [comment]
@aladdin-add You are the ESLint expert :) What should we do here? Try to strictly follow Eslint's ESTree TS including the differences with TS itself, or I create my own types and break with what exist?

Also this one is different from Eslint vs Babel vs TS itself: `var x: Array<() => void>;` If I follow ESLint's types the returned AST looks like this. Looks correct?

```ts
{
    "body": [
      {
        "declarations": [
          {
            "id": {
              "name": "x",
              "optional": false,
              "type": "Identifier",
              "typeAnnotation": {
                "type": "TypeAnnotation",
                "typeAnnotation": {
                  "type": "TSTypeReference",
                  "typeName": {
                    "name": "Array",
                    "type": "Identifier"
                  },
                  "typeParameters": {
                    "params": [
                      {
                        "params": [],
                        "returnType": {
                          "type": "TSVoidKeyword"
                        },
                        "type": "TSFunctionType",
                        "typeParameters": null
                      }
                    ],
                    "type": "TSTypeParameterInstantiation"
                  }
                }
              }
            },
            "init": null,
            "type": "VariableDeclarator"
          }
        ],
        "kind": "var",
        "type": "VariableDeclaration"
      }
    ],
    "sourceType": "script",
    "type": "Program"
  }
```

**Comment by KFlash** [comment]
@nchanged @aladdin-add What to do with Class expr & class decl? In TypeScript we got a `heritageClauses` in the returned AST as [seen here](https://github.com/microsoft/TypeScript/blob/master/src/compiler/parser.ts#L5930). 

ESLint ESTree TS types does it different as [seen here](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/typescript-estree/src/ts-estree/ts-estree.ts#L454)

I think we should be true to ESTree specs in JS parsing mode, and try to be as close as possible to TS specs in TS parsing mode.

Thoughts?

**Comment by KFlash** [comment]
Closing this as unsolved. I need to adjust the AST ouput, and create a conflict with both Babel and ESLint.
