### ISSUE TITLE
ThisKeyword as a typing for functions

### ISSUE THREAD

**Issue by nchanged** [buntis/buntis#30]
```ts
function foo (this : string, hey : number)  {
 
}
```

The following examples gives the first parameter as `Identifier` `this`
```json
{
          "type": "Identifier",
          "name": "this",
          "optional": false,
          "typeAnnotation": {
            "type": "TypeAnnotation",
            "typeAnnotation": {
              "type": "StringKeyword"
            }
          }
        }
```

`this` in functions usually point just to a typing of `this` inside a normal function

I might be wrong, but should it be better `ThisExpression` instead of the Identifier?

**Comment by KFlash** [comment]
It's an identifier

**Comment by nchanged** [comment]
you know better ;-) I've handled it as Identifier.
