### ISSUE TITLE
declaration with properties true/false break buntis

### ISSUE THREAD

**Issue by vegarringdal** [buntis/buntis#34]
Yes, Im I do weird stuff 😂 
But its still valid typescript declaration.
Its the true/false `{ true: boolean; false: boolean }` that makes it break.

**Sample:**
```ts
  const typeBool: { true: boolean; false: boolean } = {
                    true: true,
                    false: false
                };
```

Hope it helps making buntis better 😄

**Comment by vegarringdal** [comment]
btw, this did not break earlier when I tested fusebox
incase this info helps.

**Comment by KFlash** [comment]
If this case breaks Buntis I think you have to blame @nchanged . In my code it did throw `SyntaxError: Line 1, column 23: Property or signature expected`. Probably an issue in the Buntis compiler that force it into an infinity loop or something.

**Comment by vegarringdal** [comment]
I think you and @nchanged are doing an amazing job making all this work. 😄 
Not a easy task.
