### ISSUE TITLE
Running "npm run test" fails with 143 failing and 12270 passing

### ISSUE THREAD

**Issue by emnh** [buntis/buntis#44]
I'm running in WSL.

It seems that all the failing tests are with the "optional" property. Not sure, but is it missing quotes? Here's one of the test cases that fail:

1) Expressions - Arrow
       Expressions - Arrow (pass)
         f = ([[,] = g()]) => {}:

      AssertionError [ERR_ASSERTION]: Input A expected to strictly deep-equal input B:
+ expected - actual ... Lines skipped

  {
    body: [
...
                      },
-                     optional: false,
                      type: 'CallExpression'
...
    type: 'Program'
  }
      + expected - actual

                           "callee": {
                             "name": "g"
                             "type": "Identifier"
                           }
      -                    "optional": false
                           "type": "CallExpression"
                         }
                         "type": "AssignmentPattern"
                       }

      at Context.it (test/test-utils.ts:10:11)

**Comment by nchanged** [comment]
we or on `grand-refactor` branch currently. That branch will be merged to `fuse-compiler` and eventually to `master`
