### ISSUE TITLE
Things to fix 

### ISSUE THREAD

**Issue by KFlash** [buntis/buntis#6]
Very basic parser is up now, and it does TS parsing as well, **but**

- [ ] Adjust TS AST to be ESLint compatible (*with a few exceptions*)

- [ ] Implement yield and async support

- [ ] Find solutions where lookahead is needed

- [ ] Write tons of TypeScript tests

- [ ] Fix JS parsing (*from Meriyah parser*)

- [ ] Release to Beta candidate

**Comment by danielpza** [comment]
Hi, I'm glad I found this project, I'm looking forward for the first release, if you need any help let me know.

**Comment by KFlash** [comment]
Hi, @danielpza  !

I haven't had much time the last days to do anything on this project, but if you will help out it would be great! 

What's done so far is to get a basic parser running with TS support. So to take this to the next level this is the things need to be done

1. Write bunch of different TypeScript tests to figure out what doesn't work and what work and compare the AST output against the @typescript-eslint-parser ESTree AST.

2. Comment out the tests that doesn't work and / or write them on a TODO list.

After this I need to figure out how to continue writing this code without lookaheads. As in [this case](https://github.com/buntis/buntis/blob/master/src/parser.ts#L1855). Here I need to re-write the entire type annotation parsing into one single recursive function and / or parsing the identifier as argument from the `parseType` starting point.  That will fix cases like
`a | 123 & string | number & void` when we already have the `a` identifier.  So instead of this
parse

```ts
parseUnionType(isModule: 0 | 1, isTS: 0 | 1, isWebCompat: 0 | 1, inType: 0 | 1): any {
  let type = this.parseIntersectionType(isModule, isTS, isWebCompat, inType);
}
```
it need to be like this

```ts
parseUnionType(isModule: 0 | 1, isTS: 0 | 1, isWebCompat: 0 | 1, inType: 0 | 1, type: any): any {
}
```
Here `type` is passed in as an argument rather than parsed inline in the function. There are many places where functions need to be rewritten like that in the modular approach like the rest of the parser. That will also help saving memory during a single parse, and speed up things.

That's the first things to fix :)

**Comment by danielpza** [comment]
Great, I'll clone the repo and look around the project, see if I can make some tests comparing the output with the typescript eslint parser

**Comment by nchanged** [comment]
@danielpza can I interest you in a project based on bantis - an alternative compiler for typescript? I got the basics covered already (transpiling es modules into commonjs)

**Comment by danielpza** [comment]
@nchanged sure.

**Comment by KFlash** [comment]
Closing this as things have changed locale.

**Comment by KFlash** [comment]
@danielpza Do you have any time to check out the repo and maybe find cases that still don't pass?

**Comment by danielpza** [comment]
@KFlash, sure, actually last time I never got into the project, maybe you could tell me how the project is structured and how would I find what test don't work?

**Comment by KFlash** [comment]
The project is simply structured. All code is in the `src` folder, and the tests are in the `test` folder. What's needed to do now is just to try parse code and / or write complex tests and see if they break or pass. Another thing that is needed is to try to simplify much of the code in the parser.ts file - code related to typescript parsing.

**Comment by KFlash** [comment]
@danielpza Lookaheads are a big **no** in this project. Yes I know that writing a TS parser without lookaheads are nearly impossible, but still I avoid it and have done good so far. So if you run into a complex case that require a lookahead and you can't solve it, just let me know and I will fix it.
And be aware that I some places may have complicated the code to avoid lookaheads, but I still managed to optimize that part of the code and return quickly if needed.

**Comment by danielpza** [comment]
@KFlash , I played a bit with the tests and compared the output with the eslint parser, and they seem to be ok, and I didn't find any failing test on master.

> @danielpza Lookaheads are a big no in this project. Yes I know that writing a TS parser without lookaheads are nearly impossible, but still I avoid it and have done good so far. So if you run into a complex case that require a lookahead and you can't solve it, just let me know and I will fix it.
And be aware that I some places may have complicated the code to avoid lookaheads, but I still managed to optimize that part of the code and return quickly if needed.

I don't have much experience in writing parsers, so I'll probably wont be of much help there.

on a side note I had to manually install `tslib`, it is not listed as a dependency in the package.json.

**Comment by KFlash** [comment]
No failing tests on master. The tests that are failing are commented out. I just pushed a bunch of tests now and if you look at e.g. the arrow tests you will see that there are failing tests and some code that need to be adjusted / fixed before uncomment the tests  :)

What I really need to get tested and actually in lack of tests for is everything related to module code. 

Could you add tests for it? It's in the module folder for the TS tests. And if you find a issue there just let me know.

The parser now handle typescript surprisingly good :) 

Could you add `tslib` as a dependency?

**Comment by KFlash** [comment]
@danielpza TBH. There was too many issues everywhere in the code. I spent some hours yesterday to get at least the javascript parser code to pass my fuzzer, but still one nasty case left for Typescript. I published most of my changes, but my next push will contain the remaining fixes such as lexer issues etc.  
Also API have changed :)

**Comment by danielpza** [comment]
Hi @KFlash, is there a way to make the test output the full stacktrace on failing? I tried uncommenting  some of the test and seeing where they were failing but only got the first location of the error.

**Comment by KFlash** [comment]
Hi! If you try to run the tests with the `pass` method you will get the complete stack trace. I have also adjusted and fixed the error locations so it will show correct line and column.

**Comment by KFlash** [comment]
@danielpza I'm now confident enough to say that at least Javascript parses ok. I added around 11k tests for that. So shouldn't be to much issues with Typescript parsing either. I also added a few new API methods.

Today and tomorrow I'm not so much online, but for now...
 
*Could you help with this?*

1) Fix / improve TS types for everything in the code

2) Improve readme.md in root folder 

3) Deduplicate code

4) Fix non-passing tests

**Comment by danielpza** [comment]
Sure, the easiest and the ones I enjoy more are 1, 2 and 4, so I'll probably start with those.
