### ISSUE TITLE
In progress...

### ISSUE THREAD

**Issue by KFlash** [buntis/buntis#7]
The Typescript parser are now under active development after facing some serious issues related to how to understand the crazy logic in Typescript's own parser, and also lack of documentation. 

The question I sit back with is: 'Why make things super complex with no logic when it can be done simple" ?? I haven't found the answer yet :)

Also the massive use of lookaheads was a brain killer, and nested functions used to perform a simple thing....

And Babel copied all that from Typescript and mixed it with some expensive `try / catch`, `bind` and other performance killers. And missed (**and are still missing**) a lot of Typescript features.

I still can't give an exact day or date when I will do my next push because I'm in the middle of complex TS syntax. After that I'm going to add in missing JS code. 

At least over 2500 tests confirms that things are solved now, and this is what to expect on my next push:

- [x] No lookaheads or backtracking

- [x] Conforms to TS syntax (*WIP*)

- [x] Basic JS parsing

- [x] Performance

cc / @nchanged @aladdin-add

**Comment by KFlash** [comment]
**Update**: I skipped all lookaheads in the TS syntax implementation, but the fact is that the TS parser itself looks like a mess, so I was forced to do a reinterpretation from `Object expression" to `TSTypeLiteral` in parenthesized cases with and without an arrow.

Examples:  `let a: ({b, c})` and `let a: ({b}) => c`

This is cheaper and more performant than all the lookaheads and backtracking. And also less memory are used.

**Comment by KFlash** [comment]
Latest progress.

![alive_now](https://user-images.githubusercontent.com/31855118/64398647-2b34d580-d098-11e9-92fc-fbf69890519e.png)

cc / @nchanged Thoughts??

**Comment by KFlash** [comment]
@aladdin-add You are part of the ESLint team. Can you tell me **why** the ESLint parser never throws an error in 90% of the cases where  it should if you compare with Typescript itself? Is there an option to silence the error I have missed? It throws in a few places.

Try to parse this case `class Foo {protected[x: string]: any;}`

No errors!  Babel provide an error, but the error message is totally **wrong** and the error location is misplaces.

Here is the Babel output: `Unexpected token, expected "]" (1:22)`

The actual error is the `protected modifier`.  

There are too many similar cases to this with the ESLint TS parser, and it's no point to mention the Babel TS parser.... That parser ... well ... is also missing a lot of TS features and / or parses things wrong or refuse to parse.

All this issues made me waste 1 day on implementing class declaration and class expression, but at least I did it right :)

**Comment by aladdin-add** [comment]
I'm not very familiar with @typescript-eslint/parser -- it is not maintained by eslint team. :-)

acorn has a `raiseRecoverable` method to override the way non-critical errors are handled. I guess @typescript-eslint/parser for similar reason.

**Comment by aladdin-add** [comment]
refs: https://github.com/eslint/rfcs/tree/master/designs/2019-recoverable-error-handling

**Comment by KFlash** [comment]
Because of the name I thought it was something done by the eslint team. 
I used AST Explorer so doubt the errors are turned off. Just a bunch of bugs I guess :-)

Anyway. I may open a bunch of issue tickets after I have pushed my prototype code within a few days.

**Comment by KFlash** [comment]
Another funny case is this one `class H { [p2: string]; }`. None of the TS parsers except TS itself fails on it

**Comment by KFlash** [comment]
No prototype release to expect yet, but I'm soon there. Doing a TypeScript parser without lookaheads and backtracking is nearly impossible and that's what take time plus I'm making sure of 100% parity with ESTree layout.

Don't expect too much Typescript look-a-like when I I'm finally ready to push the source code. I had to reinvent the wheel... 
 
And if anyone dig into the Typescript code - don't be too confused if you notice you are parsing a object pattern inside `object type members`. It has to be done to avoid lookaheads for `type alias` etc.

**Comment by KFlash** [comment]
Closing this as the prototype is soon ready.
